- name: upgrade and update packages
  apt:
    update_cache: yes
    upgrade: yes


- name: check node version and print it to console
  command: node -v
  register: node_version
  
- name: print node version
  debug:
    msg: "node version is {{ node_version.stdout }}"

- name: check npm version and print it to console
  command: npm -v
  register: npm_version

- name: print node version
  debug:
    msg: "npm version is {{ npm_version.stdout }}"

- name: install pm2
  npm:
    name: pm2
    global: yes