- name: upgrade and update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install nvm
  become: yes
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: change permission
  become: yes
  file:
    path: "$HOME/.nvm"
    mode: "0775"
    state: file
    
- name: Install node
  become: yes
  shell: >
    $HOME/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/{{ item }}"
  loop:
    - 13.8.0

- name: install pm2
  npm:
    name: pm2
    global: yes