- name: upgrade and update packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: create directory
  become: true
  file:
    path: ~/{{ item }}
    state: directory
  with_items:
    - workspace
    - backend
- name: copy backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: ~/workspace/
  
- name: unzip backend files
  become: true
  unarchive:
    src: ~/workspace/artifacts.tar.gz
    dest: ~/workspace/
    remote_src: yes

- name: install ans start app
  command: pm2 start main.js
  args:
    chdir: ~/backend/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"