- name:  create backend directory
  file:
    path: "$HOME/backend"
    state: directory
     
- name: "unarchive backend directory"
  unarchive:
    src: artifact.tar.gz
    dest: "$HOME/backend"


- name: "install node dependencies"
  shell: |
    cd ~/backend
    npm install

- name: "start backend"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "check if backend is running"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "config pm2 to start as a service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save